#!/bin/bash

bindings="ctrl-l:accept,ctrl-e:preview-down,ctrl-y:preview-up,ctrl-d:preview-page-down,ctrl-u:preview-page-up" 
preview="if [ -f {} ]; then; bat --color always {}; else ls -a {} | awk 'NR>1 {print}'; fi"

function fuzd () {
  cd $1
  dir=`ls -a | awk 'NR>1 {print}' | fzf --layout=reverse --header=$PWD --bind="$bindings" --border=rounded --preview-window=right:70% --preview="$preview"`
  if [[ -d $dir ]]; then
    fuzd $dir
  elif [[ -f $dir ]]; then
    echo $PWD/$dir > $HOME/.vim/scripts/.vimfile
  else
    echo > $HOME/.vim/scripts/.vimfile
  fi
  exit
}

fuzd $1
