#!/bin/bash

bindings="ctrl-l:execute-silent(tmux send -t! ':edit ' {} '^M'),ctrl-e:preview-down,ctrl-y:preview-up,ctrl-d:preview-page-down,ctrl-u:preview-page-up" 
preview="bat --color always {}"

function fuzd () {
  jumps=$(tac ~/.vim/tmp/jumps)
  jumpnum=`echo "$jumps" | awk '{ print }' | fzf --ansi --layout=reverse --header=$PWD --bind="$bindings" --border=rounded --preview-window=right:50% --preview="$preview"`
  # if [[ $jumpnum ]]; then

  #   tmux send -t! ':' $jumpnum
  #   # tmux send -t! ':exe "norm ' $jumpnum '\<c-o>"^M'

  # fi
  # exit
}

fuzd "$1"
