#!/bin/bash

bindings="ctrl-l:execute-silent(tmux send -t! ':edit ' +{2}\ {1} '^M'),ctrl-e:preview-down,ctrl-y:preview-up,ctrl-d:preview-page-down,ctrl-u:preview-page-up" 
preview="bat --color always --line-range :3000 --highlight-line {2} {1}"

function fuzd () {
  cd $1
  dir=`ag --ignore $2 --ignore="node_modules" . | fzf --query="$2" --multi --delimiter=":" --layout=reverse --header=$PWD --bind="$bindings" --border=rounded --preview-window=right:50%,+{2}-4 --preview="$preview"`

  if [[ $dir ]]; then

    # Ascii hex codes for dollar and apostrophes (\x27, \x24)...
    # Allows for file names with $ dollars in the name (blame RemixJS)
    vimeditcmd=`echo "$dir" | awk '\
      BEGIN\
      {FS=":";ORS=" "}\
      NR==1\
      {print ":exe \x27 edit +"$2 "\x27 . escape(\x27" $1 "\x27, \x27\x24\x27)"}\
      NR!=1\
      {print "| exe \x27 edit +"$2 "\x27 . escape(\x27" $1 "\x27, \x27\x24\x27)"}\
    '`

    tmux send -t! "$vimeditcmd" '^M'

  fi
  exit
}

fuzd $1 "$2"
