#!/bin/bash

bindings="ctrl-e:preview-down,ctrl-y:preview-up,ctrl-d:preview-page-down,ctrl-u:preview-page-up" 

function fuzd () {
  # TODO make this work for forward jumps <c-i>
  jumpline=`cat ~/.vim/tmp/jumps | awk '{a[i++]=$0;fororback=0} END {for (j=i-1; j>=0;) print a[j--]}' | fzf --delimiter="\s+" --ansi --layout=reverse --header=$PWD --bind="$bindings" --border=rounded`

  if [[ $jumpline ]]; then

    tmux send -t! ':exe "norm ' $(echo $jumpline | awk '{print $1}') '\<c-o>"' Enter

  fi
  exit
}

fuzd "$1"
