#!/bin/bash

bindings="ctrl-l:execute-silent(tmux send -t! ':edit ' {} '^M'),ctrl-e:preview-down,ctrl-y:preview-up,ctrl-d:preview-page-down,ctrl-u:preview-page-up" 
preview="bat --color always {}"

function fuzd () {
  cd $1
  dir=`fzf --query="$2" --multi --ansi --layout=reverse --header=$PWD --bind="$bindings" --border=rounded --preview-window=right:50% --preview="$preview"`
  if [[ $dir ]]; then

    # Ascii hex codes are for dollar and apostrophes (\x27, \x24)...
    # Allows for file names with $ dollars in the name (blame RemixJS)

    vimeditcmd=`echo "$dir" | awk '\
      BEGIN\
      {ORS=" "}\
      NR==1\
      {print ":exe \x27 edit \x27 . escape(\x27" $0 "\x27, \x27\x24\x27)"}\
      NR!=1\
      {print "| exe \x27 edit \x27 . escape(\x27" $0 "\x27, \x27\x24\x27)"}\
    '` 

    tmux send -t! "$vimeditcmd" '^M'

  fi
  exit
}

fuzd $1 "$2"
