#!/bin/bash
# This almost works but the format for a tags file is wrong, tags files use the invisible "	" (do ":set list" to see this") as a field seperator (OFS)
# tags=$(ag --ignore tags --vimgrep --nomultiline "const $1[: ]|let $1[: ]|var $1[: ]|function $1[: ]|function $1[: ]\*" . | sed "s/^/$1:/g" | awk -F: '{ OFS="	"; line = "/^" $5 "$/;\""; append = "C"; print $1, $2, line, append }')
#                                                                                                                                                                                  ^ I've removed this end of line search pattern 
#                                                                                                                                                                                    because ag doesnt print the whole line
#                                                                                                                                                                                    remember! In case it breaks later on.

ag="ag"

tags=$($ag --ignore tags --vimgrep --nomultiline "^[ \t]*(export)?[ \t]*((const|var|function|class|interface|type|let|function*)|(default))[ \t]*$1 " . | sed "s/^/$1:/g" | awk -F: '{ OFS="	"; line = "/^" $5 "/;\""; append = "C"; print $1, $2, line, append }')

echo $tags

if [[ ${#tags} -lt 1 ]]; then
  echo 'None trying modules...'
  tags=$($ag --ignore tags --vimgrep --nomultiline "^[ \t]*(export)?[ \t]*((const|var|function|class|interface|type|let|function*)|(default))[ \t]*$1 " node_modules | sed "s/^/$1:/g" | awk -F: '{ OFS="	"; line = "/^" $5 "/;\""; append = "C"; print $1, $2, line, append }')
  echo $tags
fi

# Remove any existing matches...
sed -i "" "s/$1.*/d" $HOME/.vim/tags
# Update the tags file...
echo "$tags" >> $HOME/.vim/tags
